version: '3'

services:
  api:
    container_name: gopetwatch_app
    build:
      context: ./services/app
      dockerfile: Dockerfile.dev
    env_file: ./.env
    command: reflex -r '\.go$' -s -- sh -c 'go install && go run gopetwatch'
    ports:
      - 8081:8081
    volumes:
      - ./services/app:/usr/local/go/src/gopetwatch
    depends_on: 
      mysql:
        condition: service_healthy

  mysql:
    image: mysql
    container_name: gopetwatch_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: ./.env
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
