version: '3'

services:
  api:
    container_name: gopetwatch_app
    build:
      context: ./services/app
      dockerfile: Dockerfile.dev
    command: reflex -r '\.go$' -s -- sh -c 'go install && go run gopetwatch'
    ports:
      - 8081:8081
    volumes:
      - ./services/app:/usr/local/go/src/gopetwatch

  # frontend:
  #   container_name: gopetwatch_frontend
  #   build:
  #     context: ./services/frontend
  #     dockerfile: dockerfile.dev

  mysql:
    image: mysql
    container_name: gopetwatch_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=gopetwatch
      - MYSQL_USER=chancho
      - MYSQL_PASSWORD=raisin
      - MYSQL_INITDB_SKIP_TZINFO=true

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
