version: '3'

services:
  api:
    container_name: gopetwatch_app
    user: 1000:1000
    image: ghcr.io/myshkins/gopetwatch/app:latest
    env_file: ./.env
    ports:
      - 8081:8081
    volumes:
      - ./services/app:/usr/local/go/src/gopetwatch
    depends_on: 
      mysql:
        condition: service_healthy

  mysql:
    container_name: gopetwatch_mysql
    image: ghcr.io/myshkins/gopetwatch/mysql:latest
    env_file: ./.env
    ports:
      - "${MYSQL_PORT}:3306"
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080

